---
- name: Install php7.1
  yum: name={{ item }} state=present enablerepo=remi,remi-php71
  with_items:
    - php
    - php-devel
    - php-mbstring
    - php-mysqlnd
    - php-mcrypt
    - php-pear
    - php-gd
    - php-fpm
    - php-pecl-xdebug
    - php-opcache
    - php-pecl-memcached
